'use client';
import { CheckCircle, Download } from 'lucide-react';
import type { Offer } from '@loan-wizard/contracts';

export default function AcceptedPage({ params }: { params: { id: string } }) {
  function downloadKFS() {
    let offer: Offer | null = null;
    try {
      const stored = sessionStorage.getItem(`offer_${params.id}`);
      if (stored) offer = JSON.parse(stored) as Offer;
    } catch {
      /* sessionStorage unavailable — fall back to a reference-only KFS */
    }

    const inr = (n?: number | null) =>
      n == null ? '—' : `₹${Number(n).toLocaleString('en-IN')}`;
    const amount = offer?.amount ?? null;
    const emi = offer?.emi ?? null;
    const tenure = offer?.tenure_months ?? null;
    const rate = offer?.interest_rate ?? null;
    const processingFee = amount != null ? Math.round(amount * 0.01) : null;
    const totalPayable = emi != null && tenure != null ? emi * tenure : null;
    const generated = new Date().toLocaleString('en-IN', { timeZone: 'Asia/Kolkata' });

    const row = (label: string, value: string) =>
      `<tr><td class="l">${label}</td><td class="v">${value}</td></tr>`;

    const html = `<!doctype html>
<html lang="en"><head><meta charset="utf-8"/>
<meta name="viewport" content="width=device-width, initial-scale=1"/>
<title>Key Fact Statement — LoanWizard</title>
<style>
  *{box-sizing:border-box} body{font-family:-apple-system,Segoe UI,Roboto,Helvetica,Arial,sans-serif;color:#1a2b22;margin:0;padding:32px;background:#fff}
  .wrap{max-width:720px;margin:0 auto}
  .hd{border-bottom:3px solid #1f4d3a;padding-bottom:12px;margin-bottom:8px}
  .hd h1{margin:0;font-size:22px;color:#1f4d3a;letter-spacing:.3px}
  .hd p{margin:4px 0 0;font-size:12px;color:#5a6b62}
  .meta{display:flex;justify-content:space-between;font-size:12px;color:#5a6b62;margin:14px 0 18px}
  table{width:100%;border-collapse:collapse;font-size:14px}
  td{padding:10px 12px;border-bottom:1px solid #e6ece9;vertical-align:top}
  td.l{color:#5a6b62;width:55%} td.v{text-align:right;font-weight:600}
  .note{margin-top:18px;font-size:12px;color:#5a6b62;line-height:1.6;background:#f6f9f7;border:1px solid #e6ece9;border-radius:10px;padding:14px}
  .amber{margin-top:12px;font-size:12px;color:#7a5a12;background:#fdf6e3;border:1px solid #f0e2b8;border-radius:10px;padding:14px}
  .ft{margin-top:22px;font-size:11px;color:#9aa8a0;text-align:center}
  @media print{body{padding:0}}
</style></head>
<body><div class="wrap">
  <div class="hd">
    <h1>Key Fact Statement</h1>
    <p>LoanWizard &middot; Issued per RBI Digital Lending Guidelines &amp; Video-KYC framework</p>
  </div>
  <div class="meta">
    <span>Generated: ${generated} IST</span>
    <span>Session Ref: ${params.id}</span>
  </div>
  <table>
    ${row('Sanctioned Loan Amount', inr(amount))}
    ${row('Annual Interest Rate', rate != null ? `${rate}% p.a. (fixed)` : '—')}
    ${row('Tenure', tenure != null ? `${tenure} months` : '—')}
    ${row('Monthly Instalment (EMI)', inr(emi))}
    ${row('Processing Fee', processingFee != null ? `${inr(processingFee)} (1% of loan amount)` : '1% of loan amount')}
    ${row('Total Amount Payable', inr(totalPayable))}
    ${row('Prepayment / Foreclosure Charges', 'Nil after 12 months')}
    ${row('Cooling-off (Look-up) Period', '3 days — cancel without penalty')}
    ${row('Recovery &amp; Grievance', 'Grievance redressal as per lender policy')}
  </table>
  <div class="note">
    The Annual Percentage Rate (APR) reflects the all-in cost of credit including the
    interest rate and processing fee. This decision was generated by an automated,
    explainable model and is fully audit-logged with a frozen input snapshot for
    regulatory replay. Your data is processed under the Digital Personal Data
    Protection Act, 2023.
  </div>
  <div class="amber">
    <strong>Cooling-off period:</strong> You may cancel this application within 3 days
    of acceptance without penalty, per RBI digital lending norms.
  </div>
  <div class="ft">This is a system-generated Key Fact Statement and does not require a signature.</div>
</div></body></html>`;

    const blob = new Blob([html], { type: 'text/html;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `LoanWizard-KFS-${params.id}.html`;
    document.body.appendChild(a);
    a.click();
    a.remove();
    URL.revokeObjectURL(url);
  }

  return (
    <div className="min-h-screen flex items-center justify-center px-4">
      <div className="max-w-md w-full text-center">
        <CheckCircle size={64} className="text-(--color-success) mx-auto mb-6" />
        <h1 className="text-2xl font-bold text-(--color-brand) mb-2">You are all set!</h1>
        <p className="text-gray-600 mb-6">
          Our team will verify your details and reach out within 24 hours.
        </p>

        <div className="bg-gray-50 border border-gray-200 rounded-xl p-4 mb-6 text-sm text-left">
          <p className="text-gray-500 mb-1">Session Reference</p>
          <p className="font-mono font-medium text-(--color-brand) break-all">{params.id}</p>
        </div>

        <div className="bg-amber-50 border border-amber-200 rounded-xl p-4 mb-6 text-sm text-amber-900 text-left">
          <strong>Cool-off Period:</strong> You have a 3-day cool-off period per RBI digital
          lending guidelines. You may cancel this application within this period without penalty.
        </div>

        <button
          className="flex items-center justify-center gap-2 w-full border border-(--color-brand) text-(--color-brand) py-3 rounded-xl font-medium hover:bg-(--color-brand) hover:text-white transition-colors"
          onClick={downloadKFS}
        >
          <Download size={18} />
          Download Key Fact Statement
        </button>
      </div>
    </div>
  );
}
